### ISSUE TITLE
Extension does not enable on linux

### ISSUE THREAD

**Issue by 3ill** [drcika/apc-extension#131]

**Comment by sergiohdljr** [comment]
same here

**Comment by HiperDoo** [comment]
On my Arch Linux I had to run the command `sudo chown -R $(whoami) /opt/visual-studio-code` so that this extension (and after they also manipulate the UI) have the necessary permissions.

You may have to change the path where your vscode is installed

**Comment by luanlouzada** [comment]
same here in ubuntu 22.04

I ran which code and dpkg -L code

it is in the correct ubuntu folder /usr/share/code

I've already run sudo chown -R $(whoami) /usr/share/code

I restarted the extension, it doesn't work, I see that there are more people with the same problem on Linux

this solved it for me
Fix: sudo chown -R root:root /usr/share/code

Forget it, I just updated to version code_1.85.2-1705561292_amd64 and it stopped working even though I fixed it, now those same commands that I used to make it work are no longer working in this new version, but in version code_1.85.1-1702462158_amd64 it was

**Comment by sergiohdljr** [comment]
> same here in ubuntu 22.04
> 
> I ran which code and dpkg -L code
> 
> it is in the correct ubuntu folder /usr/share/code
> 
> I've already run sudo chown -R $(whoami) /usr/share/code
> 
> I restarted the extension, it doesn't work, I see that there are more people with the same problem on Linux
> 
> this solved it for me Fix: sudo chown -R root:root /usr/share/code

what this comand will actually do ?

**Comment by luanlouzada** [comment]
> > same here in ubuntu 22.04
> > I ran which code and dpkg -L code
> > it is in the correct ubuntu folder /usr/share/code
> > I've already run sudo chown -R $(whoami) /usr/share/code
> > I restarted the extension, it doesn't work, I see that there are more people with the same problem on Linux
> > this solved it for me Fix: sudo chown -R root:root /usr/share/code
> 
> what this comand will actually do ?
ChatGpt Version:

Regarding the command sudo chown -R root:root /usr/share/code, this is a command that changes the ownership of the /usr/share/code directory and all of its subdirectories and files to the root user and the root group. Here's what each part means:

sudo: Executes the command as the superuser (root), allowing you to perform actions that require administrative privileges.
chown: The command used to change the file owner and group.
root:root: Specifies the new owner (root) and group (root) for the files. The first root is the username, and the second root after the colon is the group name.
-R: Stands for "recursive," meaning the ownership change applies to the directory and all files and subdirectories within it.
/usr/share/code: The directory whose ownership you are changing.
This command effectively makes root the owner of the Visual Studio Code directory, which could resolve issues related to permissions. However, it's generally not recommended to change the ownership of system directories to a non-root user as it might introduce security risks. It's typically safer to ensure that the permissions are set correctly for your user to access the necessary files rather than changing the ownership to the root.

**Comment by cedric-costa** [comment]
Currently have somewhat the same issue on Mac. APC suddenly stopped working for me and is not able to change the ui elements of VS Code anymore.

**Comment by kszinhu** [comment]
The previous answers are correct, but in summary:

1. Change permissions

```bash
# DEBIAN
# locate vscode files
dpkg -l code

# change permissions <path to '/code' directory
sudo chown -R $(whoami) <path>

# eg:
sudo chown -R $(whoami) /usr/share/code
```

After this, enable extension

2. `CMD + SHIFT + P`
3. Click or press `Enter` on "enable apc extension"

**Comment by jesielviana** [comment]
sudo chown -R $(whoami) <path> does not work for me. I am using pop_os 22.04.

**Comment by kszinhu** [comment]
> sudo chown -R $(whoami) does not work for me. I am using pop_os 22.04.

i also use pop os, did return any error ? Or did u forget to put the visual-studio-code path?

**Comment by luanlouzada** [comment]
I managed to fix it by disabling and enabling it and it worked, after I did what I had already said in previous posts

**Comment by rchrdwllm** [comment]
same problem here in hyprland. my code installation is in `/usr/bin/code`. i tried doing...

`sudo chown -R $(whoami) /usr/bin/code`

`sudo chown -R root:root /usr/bin/code`

still doesn't work. i already tried enabling and disabling the extension.

**Comment by luanlouzada** [comment]
> same problem here in hyprland. my code installation is in `/usr/bin/code`. i tried doing...
> 
> `sudo chown -R $(whoami) /usr/bin/code`
> 
> `sudo chown -R root:root /usr/bin/code`
> 
> still doesn't work. i already tried enabling and disabling the extension.

ctrl + shift + p 
type it "enable apc extension"

**Comment by jesielviana** [comment]
> > same problem here in hyprland. my code installation is in `/usr/bin/code`. i tried doing...
> > `sudo chown -R $(whoami) /usr/bin/code`
> > `sudo chown -R root:root /usr/bin/code`
> > still doesn't work. i already tried enabling and disabling the extension.
> 
> ctrl + shift + p type it "enable apc extension"

This works for me

**Comment by rchrdwllm** [comment]
> > same problem here in hyprland. my code installation is in `/usr/bin/code`. i tried doing...
> > `sudo chown -R $(whoami) /usr/bin/code`
> > `sudo chown -R root:root /usr/bin/code`
> > still doesn't work. i already tried enabling and disabling the extension.
> 
> ctrl + shift + p type it "enable apc extension"

Worked for me, thanks! I didn't know that you had to enable it as well with ctrl + shift + p lol.

**Comment by Jervx** [comment]
If you are using Ubuntu and installed the vscode using snap, you won't be bale to ```sudo chown -R $(whoami) /usr/share/code``` because it will not exist as vscode will live in snap directory. Owning the directory will no work either. 

So install it using apt or by downloading the .deb installer from vscode website and install it using dpkg. 
You will be able to use ``` sudo chown -R $(whoami) /usr/share/code ``` and it will work.
