### ISSUE TITLE
Extension panel keeps loading indefinitely after enabling the extension in VS Code insiders

### ISSUE THREAD

**Issue by mon-jai** [drcika/apc-extension#154]
VS Code version

```
Version: 1.87.0-insider (user setup)
Commit: b8d6cdc09755c2fc8db77c179f10beb727846518
Date: 2024-02-23T11:58:40.930Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22621
```

![image](https://github.com/drcika/apc-extension/assets/91261297/66cb3b37-50a9-4788-bf02-2047ba9bd423)

**Comment by victorbadaro** [comment]
Same thing here
```
Version: 1.87.0-insider (user setup)
Commit: c11a2dd4d52e38cb92b8c464f47a7b02bb7c8762
Date: 2024-02-24T01:20:40.384Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631
```

https://github.com/drcika/apc-extension/assets/9096344/33064a1c-3643-41b9-8e90-607635d6ddc6

**Comment by TakiGuan** [comment]
Same here, is there anyone have any clues?

**Comment by jatindotdev** [comment]
was anyone able to figure out why this happens

**Comment by nbqcode** [comment]
我的也是

**Comment by xdsolraC** [comment]
Same thing here, came here after almost 1 hour trying to fix this (thinking it was related to any other VSCode setting) xD. I'm using the latest stable VSCode version btw.

**Comment by SeakMengs** [comment]
Same issue here. the current work around to solve the issue temporary is to disable the apc extension via vs code command palette whenever u want to install a new extension. it can be done by pressing ```Ctrl+Shift+P``` and search for `Enable Apc extension`, `Disable Apc extension `
![image](https://github.com/drcika/apc-extension/assets/54373229/aef58404-4c7e-43b8-a4f8-262c6096c701)

**Comment by huykirito1201** [comment]
@SeakMengs thanks, that worked !!

**Comment by minhhuy1201** [comment]
@SeakMengs thanks, it's worked !!

**Comment by mdavis1982** [comment]
I'm also seeing this now... Just spent a while trying to figure out what was going on!

**Comment by theperiscope** [comment]
Settings Sync is also affected for me, I had to disable extension for setting sync to show and work again correctly.

**Comment by diegxperez** [comment]
I don't know if I have the temporary solution but it worked for me today, I downloaded this version of Vs Code https://code.visualstudio.com/updates/v1_85, but first I deleted all the configuration, first uninstall vs code, delete everything that has to do with vs code %userprofile% || %userprofile%\AppData\Roaming. Then I disabled the automatic vscode update and added this line to my settings.json "update.mode": "none", just check in your settings that it does not update. Then install the extension it asks you to reload vscode don't do it, install your settings and download all your extensions when you are done open the command center and type "enable apc" and I think that would be it. I spent many hours looking for the solution uninstalling and installing, etc.

Another thing is that I added these lines also but I don't know if that is what is working for me because at the beginning it wasn't like that:

"security.workspace.trust.emptyWindow": false,
    "security.workspace.trust.enabled": false,
"extensions.supportUntrustedWorkspaces": {
        "drcika.apc-extension": {
            "supported": true,
            "version": "0.3.6".
        },
    },

**Comment by forivall** [comment]
My workaround right now is to leave it disabled and revert to using [Custom CSS and JS](https://github.com/be5invis/vscode-custom-css) and [Activitus Bar](https://github.com/Gruntfuggly/activitusbar) until this is properly solved. Especially since vscode added activity bar on top and compact tab height, I'm only losing custom list row height, so it's acceptable for me in the short term.

**Comment by yngwu** [comment]
There are errors in the console. Maybe it's related.
```
auxiliary.js:31 TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at toggleSettings (layout.activitybar.js:17:56)
    at exports.init (layout.activitybar.js:161:11)
    at exports.init (layout.js:10:21)
    at exports.startup (override.js:10:14)
    at where.<computed> (utils.js:8:26)
    at ne.open (desktop.main.ts:131:42)
    at async workbench.js:2604:6
exports.traceError @ auxiliary.js:31
```

**Comment by ATXadam** [comment]
This now occurs with stable - v1.87.0 that was just released; only way to get extensions working is to disable APC.

**Comment by eduardohilariodev** [comment]
I went back to version `1.86.2` until an update to fix this.

```sh
scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/58244b16004c3a94884143ac21bf97223830d7d0/bucket/vscode.json
```

**Comment by diegxperez** [comment]
> I went back to version `1.86.2` until an update to fix this.
> 
> ```shell
> scoop install https://raw.githubusercontent.com/ScoopInstaller/Extras/58244b16004c3a94884143ac21bf97223830d7d0/bucket/vscode.json
> ```

Don't forget to disable the automatic update

**Comment by tobedecided0601** [comment]
This doesn't seem to be resolved. Why closing this?

**Comment by diegxperez** [comment]
> This doesn't seem to be resolved. Why closing this?
I installed an older version of vscode and it works great, it also disables automatic updates.

**Comment by diegxperez** [comment]
> This doesn't seem to be resolved. Why closing this?

I installed an older version of vscode and it works great, it also disables automatic updates.
