### ISSUE TITLE
Vibrancy on windows

### ISSUE THREAD

**Issue by Malberee** [drcika/apc-extension#162]
How can I achieve the background blur effect? I tried the `backgroundMaterial` property and it doesn't work. 
![image](https://github.com/drcika/apc-extension/assets/82259650/78918a34-fcf7-462e-bd09-897dae22fb7a)
![image](https://github.com/drcika/apc-extension/assets/82259650/183c2370-0048-48c7-a4d9-cbcd96f5db89)

**Comment by amnweb** [comment]
Simple you can't do much, because of electron. You can remove "opacity" and you will have some type of acrylic but there is some bugs, maximize button does not work, white screen on startup and etc. Electron is sucks and that is fact.

Just example on Win11.

![Screenshot 2024-03-08 004907](https://github.com/drcika/apc-extension/assets/16545063/9075f78f-bd93-4ab8-9181-979b495dd554)

**Comment by Malberee** [comment]
Is there any way to use Vibrancy continued extension together with APC Customize UI++?

**Comment by amnweb** [comment]
It seems that the new update 1.88 moved some things forward. Now, acrylic and Mica are working.

![Screenshot 2024-04-04 192231](https://github.com/drcika/apc-extension/assets/16545063/54f82d38-b591-4d70-b150-0ce54922bfcc)

But there are strange things when VSCode is inactive; I can's find a solution to change this inactive background color or keep them all the time with acrylic.


https://github.com/drcika/apc-extension/assets/16545063/e6b099db-8ab6-45a8-94bc-4cb548cf9231

**Comment by drcika** [comment]
try
```
 "apc.electron": {
// macos - Specify how the material appearance should reflect window activity state on macOS. Must be used with the vibrancy property.
    "visualEffectState": "active" or "followWindow" or "inactive"
  },
```

**Comment by amnweb** [comment]
As I can see on the Electronjs doc, this is working only on macOS, but we are talking about Windows. I have tried this and it doesn't work.
