### ISSUE TITLE
is it possible to access the vscode API from apc.imports .js?

### ISSUE THREAD

**Issue by danielocdh** [drcika/apc-extension#194]
I want to add custom buttons and execute vscode API commands when they are clicked, via ```vscode.commands.executeCommand```

Is this possible with a .js script using apc.imports?

**Comment by drcika** [comment]
it seems that it is not possible, because in advance I have to indicate which commands I will use
for that much you can make your own extension without publishing it
through this extension you can run js, but only for dom manipulation

it all comes down to what you want to achieve

this add button to status bar
```
"apc.buttons": [
      {
        "text": "$(play)",
        "command": "npm start",
        "tooltip": "Star dev"
      },
      {
       // $(sync) vscode icon name https://code.visualstudio.com/api/references/icons-in-labels
        "text": "$(sync) build",
        "command": "npm run build",
        "alignment": 2 // 1 - left, 2 - right, default = 1
      }
]
```
