### ISSUE TITLE
Traffic lights  when sidebar is right positioned

### ISSUE THREAD

**Issue by robsontenorio** [drcika/apc-extension#3]
Hi,

Thanks for this extension! 

Is there any workaround for this?

![image](https://github.com/drcika/apc-extension/assets/118955/47878206-c74b-4ff8-9687-cf74bfc929ff)

![image](https://github.com/drcika/apc-extension/assets/118955/df76233a-476f-4599-a383-7e65248a019a)

**Comment by choco** [comment]
Hey, also running into this. Is this supposed to be fixed in the currently released version (0.0.5) ? Thanks for the great extension!
Here's my current apc settings:
```json
    "apc.activityBar": {
        "position": "bottom",
        "size": 38
    },
    "apc.statusBar": {
        "position": "editor-bottom",
    },
    "apc.electron": {
        "titleBarStyle": "hiddenInset",
        "trafficLightPosition": {
          "x": 12,
          "y": 11
        }
    },
    "window.titleBarStyle": "native"
```

**Comment by robsontenorio** [comment]
@drcika 0.0.5 did not solve it :(

Should you reopen this?

**Comment by drcika** [comment]
provide some more detail, how to reproduce

**Comment by robsontenorio** [comment]
Like this, with sidebar at `right`

```json
"workbench.sideBar.location": "right",
"window.titleBarStyle": "native",
 "apc.activityBar": {
        "position": "bottom",
        "size": 30,
    },    
    "apc.electron": {
        "titleBarStyle": "hiddenInset",    
    }

```

**Comment by drcika** [comment]
I can not reproduce
![Screenshot 2023-06-01 at 17 15 12](https://github.com/drcika/apc-extension/assets/35919606/e72770b6-5d90-4eb9-b35e-efc6c7b7fcb6)

**Comment by choco** [comment]
Ah, I also have tabs disabled, does it reproduce for you if you add this to your settings?

```
    "workbench.editor.showTabs": false,
```

**Comment by robsontenorio** [comment]
Well, I don't know why... but:

- I need to to full clean uninstall as described here https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall
- After that installed again this extension.


So, it worked ...

![image](https://github.com/drcika/apc-extension/assets/118955/43e83cb8-90db-4679-a009-6df592615cad)

**Comment by lucastnr** [comment]
~It only happens to me if I leave the sidebar on the left, it gets fixed if I move to the right.~


<details>
  <summary><s><b>Sidebar on right</b></s></summary>
<img src="https://github.com/drcika/apc-extension/assets/59018759/ec613b91-6dd2-4274-8fbf-2efb3544d6be">

</details>

<details>
  <summary><s><b>Sidebar on left</b></s></summary>
  <img src="https://github.com/drcika/apc-extension/assets/59018759/e06ffe55-28a5-4ce9-8937-6ca1942b4108">
</details>

Edit: It was fixed by changing the activity bar to the bottom:
![image](https://github.com/drcika/apc-extension/assets/59018759/63dd190e-b68e-4c28-8148-12e65c243d19)
