### ISSUE TITLE
apc.listRow affects pane headers, but not when they are collapsed

### ISSUE THREAD

**Issue by videopilot** [drcika/apc-extension#43]
Is it possible to make the pane headers separate from list row in general?

This is an extreme example, but I'm mainly thinking about the collapsed one (timeline) at the bottom matching my status bar height...

<img width="661" alt="image" src="https://github.com/drcika/apc-extension/assets/6528746/bc7f14a0-9dfe-4054-89e3-d4827bc6b7d3">

**Comment by drcika** [comment]
If I understand correctly, you want this to have special settings
![Screenshot 2023-07-07 at 08 23 37](https://github.com/drcika/apc-extension/assets/35919606/6a9234ea-05f2-4b08-a103-3afead39ec5e)

it's a bit complicated because 
vscode team treats them the same as row, they have almost the same styles and settings 

maybe I'll play around when I have time and try to separate the settings

**Comment by drcika** [comment]
maybe play around with custom settings, I don't guarantee it will work, but you can try

```
  "apc.stylesheet": {
    ".split-view-container .split-view-view:last-child .pane-header": "background: red !important"
  },
```
