### ISSUE TITLE
How to adjust terminal title bar height?

### ISSUE THREAD

**Issue by h-jia** [drcika/apc-extension#72]
<img width="257" alt="image" src="https://github.com/drcika/apc-extension/assets/29906369/f6dac7a1-1c9a-4d6c-a84e-d40cd3408d11">

**Comment by amnweb** [comment]
You can adjust **apc.sidebar.titlebar** font size because this part which you want to change using varibale --titlebar-font-size or you can do it directly with css **apc.stylesheet**

![Screenshot 2023-08-25 143636](https://github.com/drcika/apc-extension/assets/16545063/16895f40-fd91-4618-a6d0-83be3e804a04)

![Screenshot 2023-08-25 143837](https://github.com/drcika/apc-extension/assets/16545063/c26aaea2-882c-43be-b9a9-90fe117d781e)
